#!/usr/bin/env python3
import json
import string
import secrets
import os.path
import mnemonic
from dotenv import load_dotenv

load_dotenv()
MM2_RPC_IP = os.getenv('MM2_RPC_IP')
DOMAIN = os.getenv('DOMAIN')


def generate_rpc_pass(length=24):
    special_chars = "@~-_|():+"
    rpc_chars = string.ascii_letters + string.digits + special_chars
    return "".join(secrets.choice(rpc_chars) for _ in range(length))


if not os.path.exists("MM2.json"):
    rpc_password = generate_rpc_pass(16)
    m = mnemonic.Mnemonic('english')
    mm2_seed = m.generate(strength=256)
    
    with open("rpc", "w+") as f:
        f.write(f'rpc_password="{rpc_password}"\n')
    print("rpc file created.")

    conf = {
        "gui": "S7_Notary",
        "netid": 7777,
        "i_am_seed": True,
        "rpc_local_only": False,
        "rpcport": 7783,
        "rpcip": "0.0.0.0",
        "rpc_password": rpc_password,
        "passphrase": mm2_seed,
        "seednodes": ["80.82.76.214", "89.248.168.39", "65.108.90.210"],
        "userhome": "/${HOME#\"/\"}",
        "metrics": 120,
        "wss_certs": {
            "server_priv_key": f"/home/komodian/mm2_api/{DOMAIN}/privkey.pem",
            "certificate": f"/home/komodian/mm2_api/{DOMAIN}/fullchain.pem"
        }
    }
    with open("MM2.json", "w+") as f:
        json.dump(conf, f, indent=4)
    print("MM2.json file created.")
