#!/usr/bin/env python3
import os
import requests
import json

if not os.path.exists('assetchains.json'):
    r = requests.get("https://raw.githubusercontent.com/KomodoPlatform/dPoW/season-seven/iguana/assetchains.json")
    with open('assetchains.json', 'w+') as f:
        json.dump(r.json(), f)

with open('assetchains.json') as file:
    assetchains = json.load(file)
    for chain in assetchains:
        print(chain['ac_name'])
