#!/bin/bash

if [ -z "$1" ]; then
  read -p "Please specify a coin to reindex: " coin
else
  coin="${1}"
fi
service_name=$(echo $coin | awk '{print tolower($0)}')
docker compose run ${service_name} bash -c "/run.sh -reindex"
