#!/bin/bash

pip3 install -r requirements.txt

mkdir -p /home/${USER}/.zcash-params
./fetch-params.sh

source pubkey_3p.txt
if test -z "$pubkey"
then
  read -p "Enter your 3p pubkey: " pubkey
  # TODO: validate pubkey
  echo "pubkey=${pubkey}" > pubkey_3p.txt
fi
pubkey_3p=$pubkey

source pubkey.txt
if test -z "$pubkey"
then
  read -p "Enter your main pubkey: " pubkey
  # TODO: validate pubkey
  echo "pubkey=${pubkey}" > pubkey.txt
fi
pubkey_main=$pubkey

echo "Setting up .env file..."
USER_ID=$(id -u)
GROUP_ID=$(id -g)
echo "PUBKEY=${pubkey_main}" > .env
echo "PUBKEY_3P=${pubkey_3p}" >> .env
echo "USER_ID=${USER_ID}" >> .env
echo "GROUP_ID=${GROUP_ID}" >> .env
echo "DOCKER_HOST_IP=172.17.0.1" >> .env

./update "$1" "$@"
