#!/bin/bash

pip3 install -r requirements.txt

mkdir -p /home/${USER}/.zcash-params
./fetch-params.sh

source /home/${USER}/dPoW/iguana/pubkey_3p.txt
pubkey_3p=$pubkey


echo "Setting up .env file..."
USER_ID=$(id -u)
GROUP_ID=$(id -g)
echo "PUBKEY_3P=${pubkey_3p}" >> .env
echo "USER_ID=${USER_ID}" >> .env
echo "GROUP_ID=${GROUP_ID}" >> .env

./update "$1" "$@"
