#!/bin/bash
./stop
if [ -z "$1" ]
  then
    docker compose up --remove-orphans -d --build && docker compose logs -f --tail 20
  else
    docker compose up --remove-orphans -d --build $1 && docker compose logs -f --tail 20 $1
fi

