#!/bin/bash

source ./service_cli

if [[ -z ${1-} ]]; then
  for key in "${!service_cli[@]}"; do
    echo "stopping $key"
    ${service_cli[$key]} stop
  done
  echo "sleeping 30 seconds"
  sleep 30
  docker compose stop
else
  ${service_cli[$1]} stop
  echo "sleeping 30 seconds"
  sleep 30
  docker compose stop $1
fi
