#!/bin/bash

# Temp to unset docker_host_ip var
echo "Setting up .env file..."
USER_ID=$(id -u)
GROUP_ID=$(id -g)
echo "PUBKEY=${pubkey_main}" > .env
echo "PUBKEY_3P=${pubkey_3p}" >> .env
echo "USER_ID=${USER_ID}" >> .env
echo "GROUP_ID=${GROUP_ID}" >> .env

# Update repo
echo "Updating repository..."
git pull || sleep 5

# Update assetchains.json
rm assetchains.json
wget https://raw.githubusercontent.com/KomodoPlatform/dPoW/master/iguana/assetchains.json

# Creating launch files
echo "Setting up launch files..."
./configure.py launch

# Updating docker-compose yaml
echo "Updating docker-compose.yml..."
./configure.py yaml
sed "s/USERNAME/${USER}/gi" -i "docker-compose.yml"

# Setting up conf files
echo "Setting up conf files..."
./configure.py confs

# Setting up cli wrappers
echo "Setting up cli wrappers..."
./configure.py clis


if [[ "$1" == "nobuild" ]]; then
    echo "Not building docker images..."
elif [ -z "$1" ]; then
    echo "Building docker images..."
    docker compose build $@ 
    ./stop
else
    echo "Building docker image: $1"
    docker compose build $1 $@ 
    ./stop $1
fi
./link_clis.sh

echo "Done! Use ./start to launch your daemons..."
