#!/bin/bash

# Update repo
echo "Updating repository..."
git pull || sleep 5

if [[ "$1" == "mm2" ]]; then
    echo "Updating coins file..."
    wget https://raw.githubusercontent.com/KomodoPlatform/coins/master/coins -O mm2/coins
    echo "Setting up mm2 .env file..."
    USER_ID=$(id -u)
    GROUP_ID=$(id -g)
    userpass=$(./configure.py get_mm2_userpass)
    echo "USER_ID=${USER_ID}" >> mm2/.env
    echo "GROUP_ID=${GROUP_ID}" >> mm2/.env
    echo "USERPASS=${userpass}" >> mm2/.env
    echo "MM2_CONF_PATH=/home/komodian/mm2/MM2.json" > mm2/.env
    echo "MM_COINS_PATH=/home/komodian/mm2/coins" >> mm2/.env
    echo "MM_LOG=/home/komodian/mm2/mm2.log" >> mm2/.env
    ./configure.py setup_mm2
    sudo mkdir -p /etc/letsencrypt/renewal-hooks/post/
    sudo cp mm2/post-cert-renew-${USER}.sh /etc/letsencrypt/renewal-hooks/post/post-cert-renew-${USER}.sh
    # Updating docker-compose yaml
    echo "Updating docker-compose.yml..."
    ./configure.py yaml
    sed "s/USERNAME/${USER}/gi" -i "docker-compose.yml"

    # Build MM2 image
    echo "Building docker image: mm2"
    docker compose build mm2 $@ 
    docker compose stop mm2
    exit 0
fi

# Temp to unset docker_host_ip var
echo "Setting up .env file..."
USER_ID=$(id -u)
GROUP_ID=$(id -g)
echo "PUBKEY=${pubkey_main}" > .env
echo "PUBKEY_3P=${pubkey_3p}" >> .env
echo "USER_ID=${USER_ID}" >> .env
echo "GROUP_ID=${GROUP_ID}" >> .env

./stop $1


# Update assetchains.json
rm assetchains.json
wget https://raw.githubusercontent.com/KomodoPlatform/dPoW/master/iguana/assetchains.json

# Creating launch files
echo "Setting up launch files..."
./configure.py launch

# Updating docker-compose yaml
echo "Updating docker-compose.yml..."
./configure.py yaml
sed "s/USERNAME/${USER}/gi" -i "docker-compose.yml"

# Setting up conf files
echo "Setting up conf files..."
./configure.py confs

# Setting up cli wrappers
echo "Setting up cli wrappers..."
./configure.py clis


if [[ "$1" == "nobuild" ]]; then
    echo "Not building docker images..."
elif [ -z "$1" ]; then
    echo "Building docker images..."
    docker compose build $@ 
    ./stop
else
    echo "Building docker image: $1"
    docker compose build $1 $@ 
    ./stop $1
fi
./link_clis.sh

echo "Done! Use ./start to launch your daemons..."
